## NumPy
[NumPy Reference](https://docs.scipy.org/doc/numpy/reference/?v=20170731152418)

In [1]:
import numpy as np

In [2]:
# Python のリストから NumPy の配列を作成する
my_list1 = [1, 2, 3, 4]
my_arr1 = np.array(my_list1)
my_arr1

array([1, 2, 3, 4])

In [3]:
# Python のリストのリストから NumPy の多次元配列を作成する
my_lists = [[1, 2, 3, 4], [11, 22, 33, 44]]
my_arr2 = np.array(my_lists)
my_arr2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [4]:
# 配列のシェイプ
my_arr2.shape

(2, 4)

In [5]:
# 配列に格納されているデータの型
my_arr2.dtype    # NumPy の配列の要素はすべて同じデータ型である必要がある

dtype('int64')

In [6]:
# 要素が 0 の配列を作成する
my_zeros = np.zeros(5)
my_zeros

array([ 0.,  0.,  0.,  0.,  0.])

In [7]:
# 要素が 1 の配列を作成する
my_ones = np.ones([2, 2])
my_ones

array([[ 1.,  1.],
       [ 1.,  1.]])

In [8]:
# 要素が空の配列を作成する
my_empty = np.empty([3, 5])
my_empty    # 空とゼロは違う

array([[  1.72723371e-077,  -1.49457773e-154,   3.95252517e-323,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,               nan,
                      nan,  -1.49457773e-154]])

In [9]:
# Python の range() の NumPy 配列版
np.arange(10)     # NumPy 配列が返される

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#  配列どうしの計算 => それぞれの要素どうしが計算される
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# 減算
print(arr1 - arr1)

# 乗算
print(arr1 * arr1)

[[0 0 0 0]
 [0 0 0 0]]
[[ 1  4  9 16]
 [25 36 49 64]]


In [12]:
# スカラーと配列の計算

# 除算
print(1 / arr1)

# 累乗
print(arr1 * 3)

[[ 1.          0.5         0.33333333  0.25      ]
 [ 0.2         0.16666667  0.14285714  0.125     ]]
[[ 3  6  9 12]
 [15 18 21 24]]


In [13]:
# 配列の要素を取得する
arr2 = np.arange(0, 11)    # => array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# インデックスを指定して要素を取得する
print(arr2[4])

# スライスを使って要素を取得する
print(arr2[2:5])

# スライスを使って一括で要素を変更する
arr2[0:5] = 0
print(arr2)

4
[2 3 4]
[ 0  0  0  0  0  5  6  7  8  9 10]


In [14]:
# スライスを使った場合、参照渡しになる
slice_arr = arr2[5:11]    # => array([ 5,  6,  7,  8,  9, 10])
slice_arr[:] = -1     # => array([-1, -1, -1, -1, -1, -1])
arr2     # => array([ 0,  0,  0,  0,  0, -1, -1, -1, -1, -1, -1])｜元の配列が変更される

array([ 0,  0,  0,  0,  0, -1, -1, -1, -1, -1, -1])

In [15]:
# 配列をコピーする
copy_arr = arr2.copy()    # => array([ 0,  0,  0,  0,  0, -1, -1, -1, -1, -1, -1])
copy_arr[:] = 1    # => array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
arr2    # => array([ 0,  0,  0,  0,  0, -1, -1, -1, -1, -1, -1])｜元の配列は変更されない

array([ 0,  0,  0,  0,  0, -1, -1, -1, -1, -1, -1])

In [16]:
# 多次元配列の要素を取得する
arr_2d = np.array([[1, 2, 3], 
                                 [4, 5, 6], 
                                 [7, 8, 9]])

print(arr_2d[1])
print(arr_2d[2][0])
print(arr_2d[2, 0])    # arr_2d[2][0] と等価

# スライスを使って右上 2 行 2 列分を取得する
print(arr_2d[:2, 1:])

# リストのリストを指定して任意の行だけ取得する
print(arr_2d[[0, 2]])    # 0 行目と 2 行目だけ取得する

# 順番を指定して任意の行だけ取得できる
print(arr_2d[[2, 0]])

[4 5 6]
7
7
[[2 3]
 [5 6]]
[[1 2 3]
 [7 8 9]]
[[7 8 9]
 [1 2 3]]


In [17]:
# 配列の行と列を入れ替える（転置）
arr3 = np.arange(9).reshape((3, 3))    # 0 〜 8 を要素に持つ 3 行 3 列の配列を作成

print(arr3.T)
print(arr3.transpose())
print(arr3.transpose((1, 0)))    # (行, 列) = (1, 0) は行に列（1）を、列に行（0）を指定している

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [18]:
# 行列の乗算
np.dot(arr3.T, arr3)

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

In [19]:
# meshgrid() を使って配列を作成する
points = np.arange(-500, 501, 1)    # => array([-500 -499 -498 ...,  498  499  500])
dx, dy = np.meshgrid(points, points)
print(dx)
print()
print(dy)

[[-500 -499 -498 ...,  498  499  500]
 [-500 -499 -498 ...,  498  499  500]
 [-500 -499 -498 ...,  498  499  500]
 ..., 
 [-500 -499 -498 ...,  498  499  500]
 [-500 -499 -498 ...,  498  499  500]
 [-500 -499 -498 ...,  498  499  500]]

[[-500 -500 -500 ..., -500 -500 -500]
 [-499 -499 -499 ..., -499 -499 -499]
 [-498 -498 -498 ..., -498 -498 -498]
 ..., 
 [ 498  498  498 ...,  498  498  498]
 [ 499  499  499 ...,  499  499  499]
 [ 500  500  500 ...,  500  500  500]]


In [20]:
# 条件を満たす要素を取り出して配列を作成する
A = np.array([1, 2, 3, 4])
B = np.array([10, 20, 30, 40])
condition = np.array([True, True, False, False])

# リスト内包表記を使う方法
print([(a if cond else b) for a, b, cond in zip(A, B, condition)])    # 少し速度が遅い。多次元配列では使えない

# where() を使う方法
print(np.where(condition, A, B))    # => array([ 1,  2, 30, 40])

[1, 2, 30, 40]
[ 1  2 30 40]


In [21]:
# 標準正規分布の値を要素に持つ多次元配列を作成する
from numpy.random import randn
arr4 = randn(5, 5)
print(arr4)
print()

# 負の値の要素は 0 にする
print(np.where(arr4 < 0, 0, arr4))

[[-0.97830412  2.86368066  1.03293597  0.16750562 -1.11056578]
 [-0.82219329  1.314509    0.82937015 -0.78229533  0.17444413]
 [ 1.54303857 -0.77514871  3.05605687  0.3276496   0.40660897]
 [ 1.08003427  0.82839891 -1.55027598  1.10096579 -0.87912778]
 [-0.80617144  1.2977501   0.53323766 -0.40562296  0.56881663]]

[[ 0.          2.86368066  1.03293597  0.16750562  0.        ]
 [ 0.          1.314509    0.82937015  0.          0.17444413]
 [ 1.54303857  0.          3.05605687  0.3276496   0.40660897]
 [ 1.08003427  0.82839891  0.          1.10096579  0.        ]
 [ 0.          1.2977501   0.53323766  0.          0.56881663]]


In [22]:
# 配列に関する統計値
arr5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 合計値
print(arr5.sum())
print(arr5.sum(0))    # 0 を指定すると行方向に（各列の）合計が計算される
print(arr5.sum(1))    # 1 を指定すると列方向に（各行の）合計が計算される

# 平均値
print(arr5.mean())

# 標準偏差
print(arr5.std())

# 分散
print(arr5.var())

45
[12 15 18]
[ 6 15 24]
5.0
2.58198889747
6.66666666667


In [23]:
# any() と all()
arr6 = np.array([True, False, True])

print(arr6.any())    # いずれかの要素が True であれば　True が返される
print(arr6.all())    # すべての要素が True であれば True が返される

True
False


In [24]:
# 配列の要素をソートする
arr7 = randn(5)

print(arr7)
arr7.sort()    # インプレイスでソートされる
print(arr7)

[-0.07792857 -0.52305623 -0.44223493  0.3129011  -0.89475948]
[-0.89475948 -0.52305623 -0.44223493 -0.07792857  0.3129011 ]


In [25]:
# 配列の要素の重複を取り除く
countries = np.array(['Japan', 'Canada', 'USA', 'Korea', 'USA'])

print(countries)
print(np.unique(countries))

['Japan' 'Canada' 'USA' 'Korea' 'USA']
['Canada' 'Japan' 'Korea' 'USA']


In [26]:
# 配列の要素の存在を確認する
np.in1d(['USA', 'UK', 'France', 'Germany'], countries)

array([ True, False, False, False], dtype=bool)

In [27]:
# 配列をファイルに書き出す
arr8 = np.arange(5)
np.save('my_array', arr8)    # my_array.npy に書き出される

In [28]:
# 配列をファイルから読み出す
arr9 = np.load('my_array.npy')
arr9

array([0, 1, 2, 3, 4])

In [29]:
# 複数の配列を zip 形式でファイルに書き出す
np.savez('zipped_arrays.npz', x=arr8, y=arr9)

In [30]:
# zip 形式でファイルに書き出した配列を読み出す
zipped_arrays = np.load('zipped_arrays.npz')
zipped_arrays['x']

array([0, 1, 2, 3, 4])

In [31]:
# 配列をテキスト形式でファイルに書き出す
arr10 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
np.savetxt('my_array.txt', arr10, delimiter=',')    # 区切り文字にカンマを指定

In [32]:
# ! を付けるとシェルコマンドを実行できる
!cat my_array.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00


In [33]:
# テキスト形式でファイルに書き出した配列を読み出す
arr11 = np.loadtxt('my_array.txt', delimiter=',')
arr11

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.]])