## NumPy

In [1]:
import numpy as np

In [4]:
# Python のリストから NumPy の配列を作成する
my_list1 = [1, 2, 3, 4]
my_arr1 = np.array(my_list1)
my_arr1

array([1, 2, 3, 4])

In [5]:
# Python のリストのリストから NumPy の多次元配列を作成する
my_lists = [[1, 2, 3, 4], [11, 22, 33, 44]]
my_arr2 = np.array(my_lists)
my_arr2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [6]:
# 配列のシェイプ
my_arr2.shape

(2, 4)

In [8]:
# 配列に格納されているデータの型
my_arr2.dtype    # NumPy の配列の要素はすべて同じデータ型である必要がある

dtype('int64')

In [9]:
# 要素が 0 の配列を作成する
my_zeros = np.zeros(5)
my_zeros

array([ 0.,  0.,  0.,  0.,  0.])

In [11]:
# 要素が 1 の配列を作成する
my_ones = np.ones([2, 2])
my_ones

array([[ 1.,  1.],
       [ 1.,  1.]])

In [28]:
# 要素が空の配列を作成する
my_empty = np.empty([3, 5])
my_empty    # 空とゼロは違う

array([[  2.31584178e+077,  -1.49457848e-154,   3.95252517e-323,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   2.68679347e+154]])

In [32]:
# Python の range() の NumPy 配列版
np.arange(10)     # NumPy 配列が返される

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])